"""
builder_controller.py - End-to-end project build pipeline orchestrator.

Pipeline:
  1. Parse goal (goal_parser)
  2. Plan project (project_planner)
  3. Create project directory and subdirs (file_executor)
  4. Generate and write each file via LLM or deterministic rules (file_executor)
  5. Validate generated files (file_validator)
  5b. Cross-file consistency validation
  5c. Feature-completeness heuristic validation
  6. Run build commands (terminal_runner + result_checker)
  7. Repair on failure (repair_loop)
  6b. Heuristic success criteria
  8. Final summary with RUN/OPEN output

All yields are derived from real execution data - no simulated text.
"""

import logging
import re
from pathlib import Path
from typing import Any, AsyncGenerator

from core.config import config
from builder import goal_parser, project_planner
from builder.file_executor import create_project_dir, create_subdirs, create_file
from builder.terminal_runner import run_command
from builder.result_checker import check
from builder import repair_loop
from builder.file_validator import validate_file
from builder import criteria_checker

logger = logging.getLogger("presence.builder.controller")

_TOTAL_STEPS = 7

# ---------------------------------------------------------------------------
# Deterministic Fallback Content (Premium Scaffolds)
# ---------------------------------------------------------------------------

_FALLBACK_CSS = """/* Deterministic Premium Fallback CSS */
:root {
    --primary: #2563eb;
    --primary-hover: #1d4ed8;
    --bg: #f8fafc;
    --card-bg: #ffffff;
    --text: #1e293b;
    --text-muted: #64748b;
    --border: #e2e8f0;
    --radius: 8px;
    --shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    background-color: var(--bg);
    color: var(--text);
    line-height: 1.5;
}

.container {
    max-width: 1000px;
    margin: 0 auto;
    padding: 2rem;
}

nav {
    background: var(--card-bg);
    padding: 1rem 2rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1);
    margin-bottom: 2rem;
}

.card {
    background: var(--card-bg);
    border-radius: var(--radius);
    padding: 1.5rem;
    box-shadow: var(--shadow);
    margin-bottom: 1.5rem;
}

h1, h2, h3 { margin-bottom: 1rem; color: var(--text); }

button, .btn {
    display: inline-block;
    padding: 0.5rem 1rem;
    background: var(--primary);
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    transition: background 0.2s;
}

button:hover { background: var(--primary-hover); }

input, select {
    width: 100%;
    padding: 0.6rem;
    border: 1px solid var(--border);
    border-radius: 4px;
    margin-bottom: 1rem;
}

footer {
    text-align: center;
    padding: 2rem;
    color: var(--text-muted);
    font-size: 0.875rem;
}
"""

_FALLBACK_JS = """/* Deterministic Premium Fallback JS */
document.addEventListener('DOMContentLoaded', () => {
    console.log('[Presence AI] App initialized');
    
    // Add simple interactions
    const buttons = document.querySelectorAll('button');
    buttons.forEach(btn => {
        btn.addEventListener('click', () => {
            console.log('Button clicked:', btn.innerText);
        });
    });
});
"""

_FALLBACK_README = """# Project Generated by Presence AI

## Overview
This application was automatically generated based on the user's requirements.

## Features
- Premium-grade modern UI
- Clean project structure
- Built-in validation & repair logic

## Setup
1. Install dependencies: `pip install -r requirements.txt`
2. Run the application: `python app.py`

---
*Built with Presence AI Project Builder*
"""



def build_deterministic_flask_app(manifest: dict = None) -> str:
    routes = []
    if manifest and "routes" in manifest:
        for r in manifest.get("routes", []):
            if r not in ("/", "index"):
                routes.append(r)
                
    extra_routes = ""
    for r in routes:
        # Create safe function name
        fn_name = r.strip("/").replace("-", "_").replace("/", "_") or "home"
        extra_routes += f"\n@app.route('/{r.strip('/')}')\ndef {fn_name}():\n    return render_template('index.html')\n"

    return f"""# Deterministic Premium Fallback Flask App
from flask import Flask, render_template, request, jsonify, redirect, url_for
import os
import json

app = Flask(__name__)
app.config['SECRET_KEY'] = 'presence-ai-fallback-key'

# Simple JSON persistence helper
DATA_FILE = 'data/store.json'
def load_data():
    if os.path.exists(DATA_FILE):
        with open(DATA_FILE, 'r') as f: return json.load(f)
    return {{}}

def save_data(data):
    os.makedirs('data', exist_ok=True)
    with open(DATA_FILE, 'w') as f: json.dump(data, f, indent=4)

@app.route('/')
def index():
    return render_template('index.html')
{extra_routes}
@app.errorhandler(404)
def not_found(e):
    return render_template('index.html'), 404

@app.errorhandler(500)
def server_error(e):
    return "Internal Server Error (Fallback Mode)", 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)
"""


def _validate_frontend_content(content: str, rel_path: str) -> bool:
    """Rigorous in-memory check for HTML/CSS/JS/README stubs."""
    stripped = content.strip()
    if not stripped or len(stripped) < 50:
        return False
        
    lower = stripped.lower()
    
    # README check
    if rel_path.lower() == "readme.md":
        if "auto-generated" in lower and len(stripped) < 150:
            return False
        return True

    # CSS requirements: root/body, layout, and interactive
    if rel_path.endswith(".css"):
        # Require body or :root
        if "body" not in lower and ":root" not in lower:
            return False
        # Require layout/container
        if not re.search(r"\.(?:container|main|wrapper|layout|grid|flex)", lower):
            return False
        # Require interactive (button, input, nav)
        if not re.search(r"(?:button|input|nav|a:|btn)", lower):
            return False
        # counts
        selector_count = len(re.findall(r"[a-zA-Z.#\[\]:*@][^{]*\{", stripped))
        property_count = len(re.findall(r":\s*[^;]+;", stripped))
        if selector_count < 5 or property_count < 10:
            return False
        return True

    # JS requirements: real constructs
    if rel_path.endswith(".js"):
        # Real constructs count
        js_constructs = 0
        for pattern in ["function ", "const ", "let ", "var ", "=>", "document.",
                         "addEventListener", "querySelector", "fetch(", "async "]:
            if pattern in content:
                js_constructs += 1
        return js_constructs >= 2

    return True


def _sanitize_python_code(content: str) -> tuple[str, bool, bool]:
    """
    Sanitize and extract Python code.
    Returns: (sanitized_content, extraction_applied, sanity_check_passed)
    """
    content = content.replace("\r\n", "\n")
    extraction_applied = False
    
    # Priority 1: Fenced blocks
    if "```python" in content.lower():
        match = re.search(r"```python\s*(.*?)```", content, re.DOTALL | re.IGNORECASE)
        if match:
            content = match.group(1).strip()
            extraction_applied = True
    elif "```" in content:
        match = re.search(r"```[\w]*\s*(.*?)```", content, re.DOTALL)
        if match:
            content = match.group(1).strip()
            extraction_applied = True

    # Priority 2: Scan from first valid construct if it seems to start with prose
    first_lines = "\n".join(content.splitlines()[:3]).lower()
    prose_blacklist = [
        "i'm having trouble", "here's the code", "here is the", "let me explain", 
        "this code", "this script", "to fix this", "the issue is"
    ]
    if not extraction_applied and any(p in first_lines for p in prose_blacklist) or not re.match(r'^(import |from |def |class |app =|@|#)', content.lstrip()):
        lines = content.splitlines()
        code_start = -1
        valid_starts = ("import ", "from ", "def ", "class ", "app =", "@app", "if __name__", "flask")
        for i, line in enumerate(lines):
            if any(line.lstrip().startswith(v) for v in valid_starts):
                code_start = i
                break
        
        if code_start != -1:
            content = "\n".join(lines[code_start:]).strip()
            extraction_applied = True
            
    # Priority 3: Reject sanity check if still no constructs or conversational
    sanity_passed = True
    lower_content = content.lower()
    constructs = ["import ", "def ", "class ", "app =", "@app.route", "flask"]
    if not any(c in lower_content for c in constructs):
        sanity_passed = False
    if any(p in lower_content[:200] for p in prose_blacklist):
        sanity_passed = False

    return content, extraction_applied, sanity_passed


# ---------------------------------------------------------------------------
# Premium file content generation
# ---------------------------------------------------------------------------

async def _generate_file_content(
    description: str,
    project_name: str,
    tech_stack: str,
    user_request: str,
) -> str:
    """Ask LLM to generate the content for a single project file."""
    try:
        from ai.ai_router import route_llm
        system = (
            "You are an expert code generator producing premium-quality application code. "
            "Output ONLY the raw file content - no explanation, no preamble, no markdown fences, no filename header.\n\n"
            "CRITICAL RULES:\n"
            "1. Scripts must be fully self-contained and runnable with zero CLI arguments.\n"
            "2. Never use sys.argv or require command-line input. Use hardcoded defaults.\n"
            "3. Follow the user's EXACT request. Replicate specified behavior EXACTLY.\n"
            "4. DO NOT embed large HTML/CSS/JS blocks inside Python files.\n"
            "5. Assume separate files exist for templates and static assets.\n\n"
            "HTML RULES:\n"
            "- Every .html file MUST be a COMPLETE STANDALONE HTML5 document.\n"
            "- Required: <!DOCTYPE html>, <html>, <head> with <title> and <meta viewport>,\n"
            "  <body> with real content, link to /static/css/style.css,\n"
            "  link to Google Fonts (Inter or Roboto), <script src='/static/js/app.js'>.\n"
            "- Include: <nav> with app name, <main> with card-based layouts,\n"
            "  <footer> with copyright.\n"
            "- DO NOT use {% extends %} or {% block %} or Jinja2 template inheritance.\n"
            "- Use Jinja2 ONLY for dynamic data: {{ variable }}, {% for %}, {% if %}.\n"
            "- DO NOT output fragments or placeholder pages.\n\n"
            "CSS RULES:\n"
            "- Use CSS custom properties (variables) for colors and spacing.\n"
            "- Include: reset/normalize, container max-width, nav styling, card components\n"
            "  with box-shadow and border-radius, button hover/focus states with transitions,\n"
            "  input/form styling, responsive @media queries, typography with Google Fonts.\n"
            "- NEVER output placeholder CSS. Must be 200+ lines of real styles.\n\n"
            "PYTHON/FLASK RULES:\n"
            "- Use render_template() for every page route.\n"
            "- Use JSON file persistence (data/*.json) unless database explicitly requested.\n"
            "- Include proper error handling.\n"
            "- DO NOT embed HTML strings in Python.\n\n"
            "QUALITY STANDARD: Intermediate-to-premium. Think presentable demo quality.\n"
            "NOT: toy scaffold, barebones form dump, placeholder pages, minimal prototype."
        )
        prompt = (
            f"ORIGINAL USER REQUEST (follow exactly): {user_request}\n\n"
            f"File to generate: {description}\n"
            f"Project: {project_name}  Tech stack: {tech_stack}\n"
            "Rules:\n"
            "- Premium-quality, non-toy implementation\n"
            "- Modern UI aesthetics with cards, shadows, rounded corners\n"
            "- Runs with zero CLI arguments\n"
            "- Must match the user's request exactly\n"
            "- HTML files must be COMPLETE standalone documents (no Jinja extends)\n"
            "- Output ONLY the file content, no markdown fences, no filename"
        )
        content, _ = await route_llm(system_prompt=system, user_message=prompt, mode="tech")

        # Strip markdown fences if LLM wrapped the output
        if "```" in content:
            match = re.search(r"```[\w]*\n(.*?)```", content, re.DOTALL)
            if match:
                content = match.group(1).strip()
            else:
                content = re.sub(r"```[\w]*\n?", "", content)
                content = content.replace("```", "").strip()
        else:
            content = content.strip()

        # Python sanitization
        if description.endswith(".py"):
            raw_len = len(content)
            content, extraction_applied, sanity_passed = _sanitize_python_code(content)
            logger.info(f"[PY_GEN] Length={raw_len} -> {len(content)} | Extracted: {extraction_applied} | Sanity: {sanity_passed}")
            if not sanity_passed:
                logger.info(f"[PY_GEN] Output failed sanity check (prose/no code). Regenerating with fallback.")
                if "app.py" in description:
                    return build_deterministic_flask_app()
                return "# Failed to generate script (output was not Python code)\npass\n"

        # Sanity check for README
        if description.lower().endswith("readme.md") or "readme" in description.lower():
            if not _validate_frontend_content(content, "README.md"):
                logger.info("[DOCS_GEN] README fails sanity check (is placeholder). Using fallback.")
                return _FALLBACK_README

        return content
    except Exception as e:
        logger.error(f"[ERROR] File content generation failed for {description!r}: {e}")
        return f"# Auto-generated placeholder\n# Description: {description}\n"


async def _generate_css_content(project_name: str, user_request: str, features: list) -> str:
    """Dedicated CSS generator with a strong explicit prompt that demands real styles."""
    try:
        from ai.ai_router import route_llm
        feature_str = ", ".join(features) if features else "general web app"
        system = (
            "You are an expert CSS engineer producing premium-quality stylesheets. "
            "Output ONLY the raw CSS - no explanation, no markdown fences, no filename."
        )
        prompt = (
            f"Generate a complete, premium CSS stylesheet for a web application.\n\n"
            f"Project: {project_name}\n"
            f"Features: {feature_str}\n"
            f"User request: {user_request[:300]}\n\n"
            "MANDATORY - include ALL of the following:\n"
            "1. :root with CSS custom properties: --primary, --primary-dark, --bg, --bg-alt, "
            "--text, --text-muted, --card-bg, --border, --radius, --shadow\n"
            "2. * selector: box-sizing border-box, margin 0, padding 0\n"
            "3. body: font-family (Inter or Roboto via Google Fonts import at top), "
            "background, color, line-height, min-height: 100vh\n"
            "4. .container: max-width 1100px or 1200px, margin auto, padding\n"
            "5. nav: background, padding, display flex, align-items, gap, a styles, "
            "a:hover with color transition\n"
            "6. .card: background var(--card-bg), border-radius, box-shadow var(--shadow), "
            "padding, margin\n"
            "7. btn / button: padding, border-radius, background, color, border none, "
            "cursor pointer, font-size, transition\n"
            "8. button:hover: background color shift, transform: translateY(-1px)\n"
            "9. button:focus: outline with accessible color\n"
            "10. input, select, textarea: border, border-radius, padding, width 100%, "
            "font-size, focus outline style\n"
            "11. h1, h2, h3: font-size, font-weight, color, margin-bottom\n"
            "12. table: width 100%, border-collapse, th/td padding and borders, "
            "tbody tr:nth-child(even) background\n"
            "13. .form-group: margin-bottom, label display block and font-weight\n"
            "14. footer: background, color, padding, text-align center, margin-top\n"
            "15. @media (max-width: 768px): stack nav vertically, container padding, "
            "card full width\n\n"
            "Color palette must be professional and cohesive - NOT raw red/blue/green.\n"
            "Output MUST be at least 200 lines of real CSS.\n"
            "Output ONLY valid CSS. No markdown. No explanation."
        )
        content, _ = await route_llm(system_prompt=system, user_message=prompt, mode="tech")
        if "```" in content:
            match = re.search(r"```[\w]*\n(.*?)```", content, re.DOTALL)
            content = match.group(1).strip() if match else re.sub(r"```[\w]*\n?", "", content).replace("```", "").strip()
        
        final_content = content.strip()
        if _validate_frontend_content(final_content, "style.css"):
            logger.info(f"[CSS_GEN] LLM generated {len(final_content)} chars. Validation PASSED.")
            return final_content
        else:
            logger.info(f"[CSS_GEN] LLM generated {len(final_content)} chars. Validation FAILED (placeholder). Using fallback.")
            return _FALLBACK_CSS
    except Exception as e:
        logger.error(f"[ERROR] CSS generation failed: {e}")
        return _FALLBACK_CSS


async def _generate_js_content(project_name: str, user_request: str, features: list) -> str:
    """Dedicated JS generator with explicit requirements for real functional code."""
    try:
        from ai.ai_router import route_llm
        feature_str = ", ".join(features) if features else "general web app"
        system = (
            "You are an expert JavaScript engineer. "
            "Output ONLY raw JavaScript - no explanation, no markdown fences, no filename."
        )
        prompt = (
            f"Generate complete frontend JavaScript for a web application.\n\n"
            f"Project: {project_name}\n"
            f"Features: {feature_str}\n"
            f"User request: {user_request[:300]}\n\n"
            "MANDATORY:\n"
            "1. Wrap everything in DOMContentLoaded event listener\n"
            "2. At least 3 event listeners (click, submit, input, change)\n"
            "3. Form validation with user feedback (show error messages)\n"
            "4. At least 2 helper functions\n"
            "5. Use fetch() for API calls to Flask endpoints if needed\n"
            "6. Use const/let, arrow functions, template literals\n"
            "7. Add smooth UI feedback (button disable during submit, loading state)\n\n"
            "Output ONLY valid JavaScript. No markdown. No explanation."
        )
        content, _ = await route_llm(system_prompt=system, user_message=prompt, mode="tech")
        if "```" in content:
            match = re.search(r"```[\w]*\n(.*?)```", content, re.DOTALL)
            content = match.group(1).strip() if match else re.sub(r"```[\w]*\n?", "", content).replace("```", "").strip()
        
        final_content = content.strip()
        if _validate_frontend_content(final_content, "app.js"):
            logger.info(f"[JS_GEN] LLM generated {len(final_content)} chars. Validation PASSED.")
            return final_content
        else:
            logger.info(f"[JS_GEN] LLM generated {len(final_content)} chars. Validation FAILED (placeholder). Using fallback.")
            return _FALLBACK_JS
    except Exception as e:
        logger.error(f"[ERROR] JS generation failed: {e}")
        return _FALLBACK_JS


# ---------------------------------------------------------------------------
# Feature-completeness heuristic validation
# ---------------------------------------------------------------------------

def _check_feature_completeness(project_root: Path, goal: dict) -> list[str]:
    """
    Heuristic check that requested features are represented in code/UI.
    Returns list of warning strings. Empty = all features likely present.
    """
    features = goal.get("features", [])
    if not features:
        return []

    warnings = []
    features_str = " ".join(features).lower()

    # Read app.py if it exists
    app_py = project_root / "app.py"
    app_content = ""
    if app_py.exists():
        try:
            app_content = app_py.read_text(encoding="utf-8").lower()
        except Exception:
            pass

    # Read all HTML files
    html_content = ""
    templates_dir = project_root / "templates"
    if templates_dir.exists():
        for html_file in templates_dir.glob("*.html"):
            try:
                html_content += html_file.read_text(encoding="utf-8").lower() + "\n"
            except Exception:
                pass

    # Check for CRUD operations
    if any(kw in features_str for kw in ["add", "create", "new"]):
        if "post" not in app_content and "request.form" not in app_content:
            warnings.append("Feature 'add/create' requested but no POST handling found in app.py")

    if any(kw in features_str for kw in ["delete", "remove"]):
        if "delete" not in app_content and "remove" not in app_content:
            warnings.append("Feature 'delete/remove' requested but no delete logic found in app.py")

    if any(kw in features_str for kw in ["edit", "update"]):
        if "edit" not in app_content and "update" not in app_content:
            warnings.append("Feature 'edit/update' requested but no edit logic found in app.py")

    if any(kw in features_str for kw in ["filter", "search"]):
        if "filter" not in app_content and "search" not in app_content and "query" not in app_content:
            warnings.append("Feature 'filter/search' requested but no filter logic found")

    if any(kw in features_str for kw in ["summary", "overview", "dashboard"]):
        if "<h" not in html_content and "summary" not in html_content:
            warnings.append("Feature 'summary/dashboard' requested but no summary section found in HTML")

    # Check for forms in HTML if CRUD features requested
    if any(kw in features_str for kw in ["add", "create", "edit", "update"]):
        if "<form" not in html_content:
            warnings.append("CRUD features requested but no <form> found in HTML templates")

    return warnings


# ---------------------------------------------------------------------------
# Builder Controller
# ---------------------------------------------------------------------------

class BuilderController:
    """Orchestrates the full project build pipeline."""

    async def execute(self, user_text: str) -> AsyncGenerator[str, None]:
        """
        Run the full builder pipeline for a natural language project request.
        Yields status strings at each step - all derived from real execution.
        """
        dry = config.BUILDER_DRY_RUN
        if dry:
            yield "[DRY-RUN] No files will be written, no commands executed."

        # -- STEP 1: Parse goal --
        yield f"[STEP 1/{_TOTAL_STEPS}] Parsing goal..."
        goal = await goal_parser.parse(user_text)
        if "error" in goal:
            yield f"[ERROR] Goal parsing failed: {goal['error']}"
            return
        # Store the raw user request in goal so repair loop can use it for regen prompts
        goal["user_request"] = user_text
        yield (
            f"  >> Project: {goal['project_name']}  "
            f"Type: {goal['project_type']}  Stack: {goal['tech_stack']}"
        )
        if goal.get("features"):
            yield f"  >> Features: {', '.join(goal['features'])}"

        # -- STEP 2: Plan --
        yield f"[STEP 2/{_TOTAL_STEPS}] Planning project structure..."
        try:
            plan = await project_planner.plan(goal)
        except ValueError as e:
            yield f"[ERROR] Planning failed: {e}"
            return
        yield f"  >> {len(plan['files_to_create'])} files, {len(plan['commands'])} commands"
        if plan.get("manifest"):
            goal["manifest"] = plan["manifest"]
            yield f"  >> Routes: {plan['manifest']['routes']}"
            yield f"  >> Pages: {plan['manifest']['pages']}"

        # -- STEP 3: Create project directory + subdirs --
        yield f"[STEP 3/{_TOTAL_STEPS}] Creating project directory..."
        project_root: Path = create_project_dir(goal["project_name"])
        create_subdirs(project_root, plan.get("folder_structure", []))
        yield f"  >> {project_root}"

        # -- STEP 4: Generate and write files --
        yield f"[STEP 4/{_TOTAL_STEPS}] Generating {len(plan['files_to_create'])} file(s)..."
        for file_spec in plan["files_to_create"]:
            rel_path = file_spec["path"]
            description = file_spec.get("description", rel_path)

            if rel_path == "requirements.txt":
                yield f"  >> Generating: {rel_path} (Deterministic)"
                content = project_planner.build_deterministic_requirements(goal)
            elif rel_path.endswith("store.json") or rel_path.endswith("data.json"):
                yield f"  >> Generating: {rel_path} (Deterministic)"
                content = project_planner.build_deterministic_json_store()
            elif rel_path.endswith(".css"):
                yield f"  >> Generating: {rel_path} (Dedicated CSS Generator)"
                content = await _generate_css_content(
                    project_name=goal["project_name"],
                    user_request=user_text,
                    features=goal.get("features", []),
                )
            elif rel_path.endswith(".js") and rel_path.startswith("static/"):
                yield f"  >> Generating: {rel_path} (Dedicated JS Generator)"
                content = await _generate_js_content(
                    project_name=goal["project_name"],
                    user_request=user_text,
                    features=goal.get("features", []),
                )
            else:
                yield f"  >> Generating: {rel_path}"
                content = await _generate_file_content(
                    description=description,
                    project_name=goal["project_name"],
                    tech_stack=goal["tech_stack"],
                    user_request=user_text,
                )

            create_file(project_root, rel_path, content)
            yield f"  [OK] Created: {rel_path}  ({len(content)} chars)"

        build_success = True

        # -- STEP 5: Validating generated files --
        yield f"[STEP 5/{_TOTAL_STEPS}] Validating generated files..."
        for file_spec in plan["files_to_create"]:
            rel_path = file_spec["path"]
            val_result = validate_file(project_root, rel_path)

            if rel_path.endswith(".py"):
                if val_result["status"] == "success":
                    yield f"  [PY_GATE] syntax check passed: {rel_path}"
                else:
                    yield f"  [PY_GATE] syntax check FAILED: {rel_path}"

            if val_result["status"] != "success":
                yield f"  [FAIL] {rel_path} >> {val_result['error_type']}: {val_result['error_message'][:120]}"
                yield f"  >> Starting repair loop targeting {rel_path}..."

                repaired = False
                cmd_check = {
                    "status": "error",
                    "error_type": val_result["error_type"],
                    "error_message": val_result["error_message"],
                }
                async for repair_msg in repair_loop.run(
                    initial_check=cmd_check,
                    failed_command=f"Validation of {rel_path}",
                    project_root=project_root,
                    files_to_create=plan["files_to_create"],
                    target_path_override=rel_path,
                    goal=goal,
                ):
                    yield f"  {repair_msg}"
                    if repair_msg.startswith("[SUCCESS]"):
                        repaired = True

                if not repaired:
                    yield f"  [ERROR] Could not fix validation error in {rel_path}."
                    build_success = False
                    break
            else:
                yield f"  [OK] Validated: {rel_path}"

        if not build_success:
            yield ""
            yield f"[ERROR] Project completed with errors >> {project_root}"
            return

        # -- STEP 5b: Cross-File Consistency Validation --
        if goal["tech_stack"] == "flask":
            yield f"[STEP 5b/{_TOTAL_STEPS}] Cross-File Consistency Validation..."
            from builder.file_executor import read_file

            try:
                app_content = read_file(project_root, "app.py")

                # Extract all render_template() references
                found_refs = set(re.findall(r"render_template\(['\"]([^'\"]+)['\"]", app_content))

                # Build set of actual template files on disk
                templates_dir = project_root / "templates"
                actual_templates = set()
                if templates_dir.exists():
                    for f in templates_dir.iterdir():
                        if f.suffix == ".html":
                            actual_templates.add(f.name)

                # Also check manifest
                manifest_templates = {
                    f["path"].replace("templates/", "")
                    for f in plan["files_to_create"]
                    if f["path"].startswith("templates/")
                }

                yield f"  [CHECK] render_template refs: {sorted(found_refs)}"
                yield f"  [CHECK] Actual template files: {sorted(actual_templates)}"

                missing = found_refs - actual_templates
                if missing:
                    yield f"  [FAIL] Missing templates: {sorted(missing)}"
                    yield f"  >> Starting Route Harmonization repair on app.py..."

                    cmd_check = {
                        "status": "error",
                        "error_type": "missing_template",
                        "error_message": (
                            f"app.py references {sorted(missing)}, but only "
                            f"{sorted(actual_templates)} exist. "
                            "PATCH the Python routes to use ONLY the existing templates."
                        ),
                    }

                    repaired = False
                    async for repair_msg in repair_loop.run(
                        initial_check=cmd_check,
                        failed_command="Cross-file template reference validation",
                        project_root=project_root,
                        files_to_create=plan["files_to_create"],
                        target_path_override="app.py",
                        goal=goal,
                    ):
                        yield f"  {repair_msg}"
                        if repair_msg.startswith("[SUCCESS]"):
                            repaired = True

                    if not repaired:
                        yield f"  [ERROR] Could not harmonize routes. Build fails."
                        build_success = False
                        yield ""
                        yield f"[ERROR] Project completed with errors >> {project_root}"
                        return
                else:
                    yield f"  [OK] Cross-file consistency OK."

                # -- Check static asset references in HTML --
                for tmpl_file in (templates_dir.iterdir() if templates_dir.exists() else []):
                    if tmpl_file.suffix == ".html":
                        tmpl_content = tmpl_file.read_text(encoding="utf-8")
                        if "/static/css/style.css" in tmpl_content:
                            css_path = project_root / "static" / "css" / "style.css"
                            if not css_path.exists():
                                yield f"  [WARN] {tmpl_file.name} references style.css but file missing"
                        if "/static/js/app.js" in tmpl_content:
                            js_path = project_root / "static" / "js" / "app.js"
                            if not js_path.exists():
                                yield f"  [WARN] {tmpl_file.name} references app.js but file missing"

            except FileNotFoundError:
                yield "  [SKIP] app.py missing, skipping cross-file check."

        # -- STEP 5c: Feature-Completeness Heuristic --
        if build_success and goal.get("features"):
            yield f"[STEP 5c/{_TOTAL_STEPS}] Feature-completeness check..."
            feat_warnings = _check_feature_completeness(project_root, goal)
            if feat_warnings:
                for w in feat_warnings:
                    yield f"  [WARN] {w}"
                yield "  [NOTE] Feature gaps detected but not blocking build."
            else:
                yield "  [OK] Feature completeness check passed."

        # -- STEP 6: Run commands --
        if not plan["commands"]:
            yield f"[STEP 6/{_TOTAL_STEPS}] No commands to run -- skipping."
        else:
            yield f"[STEP 6/{_TOTAL_STEPS}] Running {len(plan['commands'])} command(s)..."

        for cmd in plan["commands"]:
            yield f"  >> Running: {cmd}"
            result = run_command(cmd, project_root)
            cmd_check = check(result, cmd)

            if cmd_check["status"] == "success":
                yield f"  [OK] Command succeeded: {cmd}"
                continue

            # -- STEP 7: Repair on failure --
            yield f"[STEP 7/{_TOTAL_STEPS}] Runtime error >> {cmd_check['error_type']}: {cmd_check['error_message'][:100]}"
            yield f"  >> Starting repair loop..."

            repaired = False
            async for repair_msg in repair_loop.run(
                initial_check=cmd_check,
                failed_command=cmd,
                project_root=project_root,
                files_to_create=plan["files_to_create"],
                goal=goal,
            ):
                yield f"  {repair_msg}"
                if repair_msg.startswith("[SUCCESS]"):
                    repaired = True

            if not repaired:
                yield f"  [ERROR] Could not fix: {cmd}. Build degraded."
                build_success = False

        # -- STEP 6b: Validate Success Criteria --
        criteria = plan.get("success_criteria", [])
        if criteria and build_success:
            yield f"[STEP 6b/{_TOTAL_STEPS}] Verifying heuristic success criteria..."
            failures = criteria_checker.verify_criteria(project_root, criteria)
            if failures:
                for f in failures:
                    yield f"  [FAIL] {f['error']} (Rule: {f['rule']})"
                yield "  [ERROR] Project failed success criteria."
                build_success = False
            else:
                yield "  [OK] All success criteria passed."

        # -- Final summary --
        yield ""
        
        # Determine if fallback was used
        fallback_used = False
        app_path = project_root / "app.py"
        if app_path.exists():
            try:
                if "Deterministic Premium Fallback Flask App" in app_path.read_text(encoding="utf-8"):
                    fallback_used = True
            except: pass

        feature_warnings = _check_feature_completeness(project_root, goal)
        
        status_msg = "[SUCCESS] Project built and verified!"
        if not build_success:
            status_msg = "[ERROR] Project build FAILED. Check logs above."
        elif fallback_used:
            status_msg = "[DEGRADED] Project is RUNNABLE but used fallback deterministic scaffolds."
        elif feature_warnings:
            status_msg = "[PARTIAL SUCCESS] Project is running, but some requested features might be missing."

        yield "=" * 60
        yield f"  {status_msg}"
        yield "=" * 60
        yield f"  Location: {project_root}"
        
        if not build_success:
            yield "  [!] Action Required: Review the errors above."
        elif fallback_used:
            yield "  NOTE: Major generation failures occurred; system used safety scaffolds to ensure run-readiness."
        
        if feature_warnings and build_success:
            yield "  Feature Gaps Detected:"
            for w in feature_warnings:
                yield f"    - {w}"
        
        if build_success:
            yield ""
            yield "  To run your app:"
            startup_cmd = "python app.py"
            if goal["tech_stack"] != "flask" and plan["commands"]:
                startup_cmd = plan["commands"][-1]
            yield f"    cd \"{project_root}\""
            yield f"    {startup_cmd}"
            
            if goal["project_type"] == "web" or goal["tech_stack"] == "flask":
                yield ""
                yield "  Open in browser:"
                yield "    http://127.0.0.1:5000"
        yield "=" * 60
        yield ""
