"""
criteria_checker.py — Heuristic code quality verification.

Uses simple heuristic strings generated by project_planner.py
to verify the generated files meet minimum requirements (e.g. routes actually exist).

Supported criteria formats:
  - "regex:filepath:pattern"   (Checks if regex pattern exists in file)
  - "exists:filepath"          (Checks if file was created)
"""

import logging
import re
from pathlib import Path

logger = logging.getLogger("presence.builder.criteria_checker")

def verify_criteria(project_root: Path, criteria: list[str]) -> list[dict]:
    """
    Run all criteria against the generated project.
    Returns a list of failed checks. Empty list means full success.
    """
    failures = []

    for rule in criteria:
        try:
            if rule.startswith("regex:"):
                # Format: regex:path/to/file:pattern
                parts = rule.split(":", 2)
                if len(parts) != 3:
                    logger.warning(f"[CRITERIA] Invalid regex rule format: {rule}")
                    continue
                
                _, rel_path, pattern = parts
                file_path = (project_root / rel_path).resolve()
                
                if not file_path.exists():
                    failures.append({"rule": rule, "error": f"File {rel_path} not found"})
                    continue
                
                content = file_path.read_text(encoding="utf-8")
                if not re.search(pattern, content, re.IGNORECASE):
                    failures.append({"rule": rule, "error": f"Pattern '{pattern}' missing in {rel_path}"})
            
            elif rule.startswith("exists:"):
                # Format: exists:path/to/file
                _, rel_path = rule.split(":", 1)
                file_path = (project_root / rel_path).resolve()
                if not file_path.exists():
                    failures.append({"rule": rule, "error": f"File {rel_path} not found"})

            elif "exit_code" in rule or "validated" in rule or "runtime errors" in rule:
                 # Skip legacy dynamic rules that are handled by other pipeline steps.
                 pass
            
            else:
                 logger.debug(f"[CRITERIA] Unrecognized heuristic rule, skipping: {rule}")
                 
        except Exception as e:
            logger.error(f"[CRITERIA] Evaluator crashed on rule '{rule}': {e}")
            failures.append({"rule": rule, "error": f"Crash: {e}"})

    return failures
